# Generated by Django 4.1.1 on 2024-01-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuMingleeApp', '0002_type_restaurant_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
