# Generated by Django 4.1.1 on 2024-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuMingleeApp', '0007_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
