# Generated by Django 4.1.1 on 2024-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuMingleeApp', '0009_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
