# Generated by Django 4.1.1 on 2024-01-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuMingleeApp', '0010_vote_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuMingleeApp.employee'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuMingleeApp.restaurant'),
        ),
    ]
